# Generated by Django 5.1.1 on 2024-09-26 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(db_index=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='developer_level',
            field=models.CharField(blank=True, db_index=True, default='Уровень не определен', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, default='+996', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
