# Generated by Django 5.1.1 on 2024-09-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Enter book title')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Upload book cover image')),
                ('author', models.CharField(max_length=255, verbose_name='Enter author name')),
                ('description', models.TextField(verbose_name='Write a description of the book')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enter price')),
                ('publication_year', models.IntegerField(verbose_name='Enter year of publication')),
                ('pages', models.IntegerField(verbose_name='Enter number of pages')),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('History', 'History'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=50, verbose_name='Select genre')),
                ('url', models.URLField(verbose_name='Enter book URL')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter email for inquiries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
