# Generated by Django 5.1.1 on 2024-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price_reviewbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Enter author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(db_index=True, null=True, verbose_name='Write a description of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Enter email for inquiries'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('History', 'History'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], db_index=True, max_length=50, null=True, verbose_name='Select genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(db_index=True, null=True, upload_to='books/', verbose_name='Upload book cover image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Enter number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Enter price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Enter year of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Enter book title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(db_index=True, null=True, verbose_name='Enter book URL'),
        ),
    ]
