# Generated by Django 5.1.1 on 2024-09-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewBook',
        ),
    ]
