# Generated by Django 5.1.1 on 2024-09-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_movie', to='tv_show.movie'),
        ),
    ]
